version: '3.9'
services:
  db:
    image: postgres:16 # You can specify a different version if needed
    container_name: nest_crud_mysql # A custom name for your container
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_crud # Optional: Name of a database to create on startup
      POSTGRES_USER: nest # Optional: Name of a user to create on startup
      POSTGRES_PASSWORD: nest # Optional: Password for the user
    ports:
      - "3306:5432" # Map host port 3306 to container port 3306
    volumes: 
    - pgdata_data:/var/lib/postgresql/data

volumes:
  pgdata_data: #volume para armazenar dados do MySQL